build:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**/*"
          - "pyproject.toml"
          - ".pre-commit-config.yaml"

integration:
  - changed-files:
      - any-glob-to-any-file:
          - "custom_components/**/*"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "README.md"
          - "LICENSE"
          - "doc/**/*"
